import { initialize, minify, validate } from "wgslender";

import { createTreeShader } from "../src/tree-shader.js";

const ENTRY_POINTS = [
  "hybrid_neighbor_blocks", "hybrid_neighbor_prefixes", "hybrid_scan_blocks",
  "hybrid_scan_prefixes", "hybrid_mix_tree_up",
  "tree_global", "tree_down_classify",
];
const MINIFIED_ENTRY_POINTS = "abcdefg";
const STRUCT_MEMBERS = {
  stream_count: "a",
  token_count: "b",
  block_count: "c",
  tree_nodes: "d",
  block_start: "e",
  tree_offset: "f",
  tree_power: "g",
  local_index: "h",
};

export async function generatedShaderContents(model) {
  await initialize();
  const minifyShader = (f16) => {
    let source = createTreeShader(model, { f16 });
    for (let index = 0; index < ENTRY_POINTS.length; index++) {
      source = source.replace(
        `fn ${ENTRY_POINTS[index]}(`,
        `fn ${MINIFIED_ENTRY_POINTS[index]}(`,
      );
    }
    for (const [name, minified] of Object.entries(STRUCT_MEMBERS)) {
      source = source.replaceAll(name, minified);
    }
    const result = minify(source, {
      minifyWhitespace: true,
      minifyIdentifiers: true,
      minifySyntax: true,
      treeShaking: true,
      mangleExternalBindings: true,
    });
    if (result.errors.length) {
      throw new Error(`WGSL minification failed: ${result.errors.map(({ message }) => message).join("; ")}`);
    }
    const validation = validate(result.code);
    if (!validation.valid) {
      throw new Error(`Minified WGSL is invalid: ${validation.diagnostics.map(({ message }) => message).join("; ")}`);
    }
    return result.code;
  };
  const f16Shader = minifyShader(true);
  const derivedF32Shader = f16Shader.slice("enable f16;".length).replaceAll("f16", "f32");
  const validation = validate(derivedF32Shader);
  if (!validation.valid) {
    throw new Error(`Derived f32 WGSL is invalid: ${validation.diagnostics.map(({ message }) => message).join("; ")}`);
  }
  return `// Generated by \`pnpm build:core\` or \`pnpm model:promote\`. Do not edit by hand.\n` +
    `const shader = ${JSON.stringify(f16Shader)};\n` +
    `export const TREE_ENTRY_POINTS = ${JSON.stringify(MINIFIED_ENTRY_POINTS)};\n` +
    `export const createPromotedShader = (f16) => f16 ? shader : shader.slice(11).replaceAll("f16", "f32");\n`;
}
