// Generated by `pnpm benchmark:correctness`. Do not edit by hand.
export const correctnessComparison = Object.freeze({
  "runId": "20260909T074331.018Z",
  "normalizationVersion": 3,
  "generatedAt": "2026-09-09T07:44:46.184Z",
  "period": "2026-Q1",
  "source": "https://innovationgraph.github.com/global-metrics/programming-languages",
  "verificationSha256": "3aa93cafea841d0a0aa127b280ff660d1ec8b8d3b032ab000b5f66524e9129e8",
  "languages": [
    "JavaScript",
    "Python",
    "TypeScript",
    "Shell",
    "Dockerfile",
    "Java",
    "C++",
    "C",
    "Makefile",
    "Batchfile",
    "PHP",
    "C#",
    "PowerShell",
    "CMake",
    "Kotlin",
    "Ruby",
    "Swift",
    "Go",
    "PLpgSQL",
    "Rust",
    "Objective-C",
    "Lua",
    "Dart",
    "Procfile",
    "Assembly"
  ],
  "files": 1103,
  "rows": [
    {
      "label": "Shiki",
      "value": 100,
      "coverage": 100
    },
    {
      "label": "gpu-lexer",
      "value": 90.35330214502152,
      "coverage": 100,
      "featured": true
    },
    {
      "label": "Prism.js",
      "value": 86.92883214054152,
      "coverage": 100,
      "featured": false
    },
    {
      "label": "Highlight.js",
      "value": 84.3147193963285,
      "coverage": 100,
      "featured": false
    },
    {
      "label": "Starry Night",
      "value": 81.88801618014966,
      "coverage": 100,
      "featured": false
    },
    {
      "label": "Sugar High",
      "value": 75.92748748838441,
      "coverage": 90.08322536253817,
      "featured": false
    }
  ]
});
