// Generated by `pnpm benchmark:correctness`. Do not edit by hand.
export const correctnessComparison = Object.freeze({
  "runId": "20260909T074331.018Z",
  "normalizationVersion": 4,
  "generatedAt": "2026-09-16T03:09:21.599Z",
  "period": "2026-Q1",
  "source": "https://innovationgraph.github.com/global-metrics/programming-languages",
  "verificationSha256": "3aa93cafea841d0a0aa127b280ff660d1ec8b8d3b032ab000b5f66524e9129e8",
  "labelSource": "regenerated-shiki-source",
  "labelsSha256": "1ab419ebcebbec743058b2f070689838815b6f0c3e9157cd63af5a861f6f2b36",
  "languages": [
    "JavaScript",
    "Python",
    "TypeScript",
    "Shell",
    "Dockerfile",
    "Java",
    "C++",
    "C",
    "Makefile",
    "Batchfile",
    "PHP",
    "C#",
    "PowerShell",
    "CMake",
    "Kotlin",
    "Ruby",
    "Swift",
    "Go",
    "PLpgSQL",
    "Rust",
    "Objective-C",
    "Lua",
    "Dart",
    "Procfile",
    "Assembly"
  ],
  "files": 1103,
  "rows": [
    {
      "label": "Shiki",
      "value": 100,
      "coverage": 100
    },
    {
      "label": "Prism.js",
      "value": 84.05031137838132,
      "coverage": 100,
      "featured": false
    },
    {
      "label": "gpu-lexer",
      "value": 76.79398205145654,
      "coverage": 100,
      "featured": true
    },
    {
      "label": "Sugar High",
      "value": 73.61166045791462,
      "coverage": 90.08322536253817,
      "featured": false
    },
    {
      "label": "Starry Night",
      "value": 72.25013671144764,
      "coverage": 100,
      "featured": false
    },
    {
      "label": "Highlight.js",
      "value": 70.12005513061939,
      "coverage": 100,
      "featured": false
    }
  ]
});
