// Generated by `pnpm model:promote`. Do not edit by hand.
export const modelStats = Object.freeze({
  "runId": "20260916T055435.785Z",
  "accuracy": 0.8301724567612022,
  "shikiDisagreementRate": 0.16982754323879778,
  "trainingTokensPerEpoch": 4679585,
  "modelParameters": 41321,
  "modelWeightBytes": 30991,
  "modelWeightBits": 6,
  "languageAccuracyDistribution": [
    {
      "range": "95–100%",
      "languages": [
        "angular-html",
        "angular-ts",
        "apex",
        "jsx"
      ]
    },
    {
      "range": "90–<95%",
      "languages": [
        "actionscript-3",
        "dart",
        "go",
        "hcl",
        "javascript",
        "proto",
        "python",
        "rust",
        "solidity",
        "svelte",
        "swift",
        "toml",
        "tsx"
      ]
    },
    {
      "range": "80–<90%",
      "languages": [
        "astro",
        "c",
        "cmake",
        "coffeescript",
        "cpp",
        "csharp",
        "css",
        "docker",
        "gdscript",
        "glsl",
        "haxe",
        "hlsl",
        "html",
        "java",
        "json",
        "odin",
        "php",
        "powershell",
        "ruby",
        "shell",
        "shellscript",
        "typescript",
        "wgsl",
        "xml",
        "xsl"
      ]
    },
    {
      "range": "70–<80%",
      "languages": [
        "bat",
        "bicep",
        "c3",
        "fortran-fixed-form",
        "haskell",
        "kotlin",
        "make",
        "nginx",
        "nim",
        "nix",
        "objective-cpp",
        "r",
        "scala",
        "vue",
        "yaml",
        "zig"
      ]
    },
    {
      "range": "60–<70%",
      "languages": [
        "ada",
        "d",
        "diff",
        "fortran-free-form",
        "groovy",
        "hack",
        "less",
        "lua",
        "markdown",
        "matlab",
        "prisma",
        "puppet",
        "qml",
        "scss",
        "system-verilog"
      ]
    },
    {
      "range": "50–<60%",
      "languages": [
        "asm",
        "awk",
        "emacs-lisp",
        "gherkin",
        "graphql",
        "julia",
        "mdx",
        "objective-c",
        "perl",
        "shaderlab",
        "sql",
        "viml",
        "wasm"
      ]
    },
    {
      "range": "<50%",
      "languages": [
        "jinja",
        "liquid",
        "razor",
        "vala",
        "vb"
      ]
    }
  ]
});
