// Generated by wgsl.py -- do not edit.
// Multi-entry-point pipeline; see the module docstring for the split.

const DIM: u32 = 64u;
const EDIM: u32 = 32u;
const HEAD_HIDDEN: u32 = 96u;
const NCLASS: u32 = 9u;
const KSIZE: u32 = 5u;
const TILE: u32 = 16u;
const TILE_POOL: u32 = 4u;
const MAX_JOBS: u32 = 64u;
const NREG: u32 = 8u;
const EMB_P: u32 = 0u;
const EMB_W: u32 = 1012u;
const EMB_B: u32 = 3u;
const EMB_S: u32 = 0u;
const UP_P: u32 = 3036u;
const UP_W: u32 = 64u;
const UP_B: u32 = 1u;
const UP_S: u32 = 11u;
const UP_BI: u32 = 75u;
const FD_P: u32 = 3100u;
const FD_W: u32 = 128u;
const FD_B: u32 = 1u;
const FD_S: u32 = 139u;
const FD_BI: u32 = 171u;
const FU_P: u32 = 3228u;
const FU_W: u32 = 384u;
const FU_B: u32 = 1u;
const FU_S: u32 = 203u;
const FU_BI: u32 = 587u;
const GS_P: u32 = 5700u;
const GS_W: u32 = 512u;
const GS_B: u32 = 1u;
const GS_S: u32 = 3323u;
const GS_BI: u32 = 3387u;
const GG_P: u32 = 6212u;
const GG_W: u32 = 128u;
const GG_B: u32 = 1u;
const GG_S: u32 = 3451u;
const GG_BI: u32 = 3515u;
const HH_P: u32 = 6340u;
const HH_W: u32 = 384u;
const HH_B: u32 = 1u;
const HH_S: u32 = 3579u;
const HH_BI: u32 = 3675u;
const HO_P: u32 = 6724u;
const HO_W: u32 = 27u;
const HO_B: u32 = 1u;
const HO_S: u32 = 3771u;
const HO_BI: u32 = 3780u;
const HNORM_F: u32 = 4942u;
const FS_F: u32 = 3790u;
const FN_F: u32 = 3982u;
const NLAYER: u32 = 3u;
const FILM_RANK: u32 = 32u;
const DG_F: u32 = 4878u;
const HW_F: u32 = 3789u;
const FIELD_ROW: array<u32, 10> = array<u32, 10>(0u, 4u, 12u, 140u, 268u, 780u, 908u, 924u, 940u, 972u);
const FLAG_ROW: u32 = 1004u;
const NFIELD: u32 = 10u;
const NFLAG: u32 = 8u;

// One job per workgroup_id.y. Batched calls dispatch every job together so they
// run concurrently and share one readback.
struct Job {
    token_count: u32,
    token_offset: u32,   // slice of the shared token/output buffers
    stage: u32,          // reserved for the stage-diff test harness
    stride: u32,         // per-job hidden-state stride, = maxTokens * DIM
};

@group(0) @binding(0) var<storage, read>       tokens : array<u32>;
@group(0) @binding(1) var<storage, read>       planes : array<u32>;
@group(0) @binding(2) var<storage, read>       fp     : array<f32>;
@group(0) @binding(3) var<storage, read_write> hid    : array<f32>;
@group(0) @binding(4) var<storage, read_write> scratch: array<f32>;
@group(0) @binding(5) var<storage, read_write> out_cls: array<u32>;
// A uniform array, not storage: Tint treats uniform loads indexed by a builtin
// as uniform, which is what allows `workgroupBarrier` inside job-dependent
// loops. A storage load here makes every barrier in the kernel illegal.
@group(0) @binding(6) var<uniform>             jobs   : array<Job, MAX_JOBS>;

var<workgroup> tA  : array<f32, 1536>;   // TILE x DIM, reused as TILE x HEAD_HIDDEN
var<workgroup> tB  : array<f32, 2048>;   // TILE x 2*DIM
var<workgroup> tP  : array<f32, 1024>;   // TILE_POOL x 4*DIM
var<workgroup> red : array<f32, 64>;
var<workgroup> lg  : array<f32, 144>;    // TILE x NCLASS

// WGSL's tanh is computed as (e^2x - 1)/(e^2x + 1) on some backends, so a
// moderately large argument overflows to inf/inf = NaN instead of saturating.
// The GELU in the head reaches that range routinely -- its cubic term hits ~90 at
// an input of ~14 -- which silently turned whole tokens into NaN logits and made
// argmax fall back to class 0. Clamping is exact: tanh(15) and sigmoid(30) are
// already 1.0 in f32.
fn tanh_s(x: f32) -> f32 { return tanh(clamp(x, -15.0, 15.0)); }
fn sigmoid_s(x: f32) -> f32 { return 1.0 / (1.0 + exp(-clamp(x, -30.0, 30.0))); }
// Matches torch.nn.functional.softplus's numerically-stable form: linear past
// the point where exp(x) would overflow or the log1p term becomes a no-op.
fn softplus_s(x: f32) -> f32 { return select(log(1.0 + exp(x)), x, x > 20.0); }

// k-bit weight from bit-planes. Used only where the row index depends on data:
// the embedding table and the depthwise kernel.
fn wgt(base: u32, wpp: u32, bits: u32, idx: u32, scale: f32) -> f32 {
    var c: u32 = 0u;
    let w = idx >> 5u;
    let b = idx & 31u;
    for (var p: u32 = 0u; p < bits; p = p + 1u) {
        c = c | (((planes[base + p * wpp + w] >> b) & 1u) << p);
    }
    if (bits == 1u) { return select(-scale, scale, c == 1u); }
    return (f32(c) - f32(1u << (bits - 1u))) * scale;
}

// Every projection is 1-bit and its rows are a multiple of 32 wide, so a whole
// row is 1-8 u32 held in registers for the life of the dispatch. Each MAC is
// then a register shift and a sign select rather than a dependent global load.
fn m1(w: u32, k: u32, x: f32) -> f32 { return select(-x, x, ((w >> k) & 1u) == 1u); }

fn dotA32(w: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w, k, tA[base + k]); }
    return a;
}
fn dotA64(w0: u32, w1: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tA[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tA[base + 32u + k]); }
    return a;
}
fn dotA96(w0: u32, w1: u32, w2: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tA[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tA[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tA[base + 64u + k]); }
    return a;
}
fn dotA128(w0: u32, w1: u32, w2: u32, w3: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tA[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tA[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tA[base + 64u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w3, k, tA[base + 96u + k]); }
    return a;
}
fn dotRed64(w0: u32, w1: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, red[k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, red[32u + k]); }
    return a;
}
fn dotRed32(w: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w, k, red[k]); }
    return a;
}
fn dotB128(w0: u32, w1: u32, w2: u32, w3: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tB[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tB[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tB[base + 64u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w3, k, tB[base + 96u + k]); }
    return a;
}
fn dotB32(w: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w, k, tB[base + k]); }
    return a;
}

fn tw0(o: u32, i: u32) -> u32 { return tokens[(o + i) * 2u]; }
fn tw1(o: u32, i: u32) -> u32 { return tokens[(o + i) * 2u + 1u]; }
fn tok_kind(o: u32, i: u32)  -> u32 { return  tw0(o, i)        & 3u; }
fn tok_flags(o: u32, i: u32) -> u32 { return (tw0(o, i) >> 19u) & 255u; }

fn field_id(o: u32, i: u32, f: u32) -> u32 {
    switch f {
        case 0u:  { return  tw0(o, i)        & 3u; }
        case 1u:  { return (tw0(o, i) >>  2u) & 7u; }
        case 2u:  { return (tw0(o, i) >>  5u) & 127u; }
        case 3u:  { return (tw0(o, i) >> 12u) & 127u; }
        case 4u:  { return  tw1(o, i)        & 1023u; }
        case 5u:  { return (tw1(o, i) >> 10u) & 127u; }
        case 6u:  { return (tw1(o, i) >> 17u) & 15u; }
        case 7u:  { return (tw1(o, i) >> 21u) & 15u; }
        case 8u:  { return (tw1(o, i) >> 25u) & 31u; }
        default:  { return (tw0(o, i) >> 27u) & 31u; }
    }
}

// Per-token inverse RMS for a tile, computed by the first TILE threads.
fn tile_rms(d: u32, n: u32) {
    if (d < n) {
        var s: f32 = 0.0;
        for (var k: u32 = 0u; k < DIM; k = k + 1u) {
            let v = tA[d * DIM + k];
            s = s + v * v;
        }
        red[d] = inverseSqrt(s / f32(DIM) + 1e-6);
    }
}


@compute @workgroup_size(64)
fn embed(@builtin(local_invocation_id) lid: vec3<u32>,
         @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let off = job.token_offset;
    let hbase = job.stride * wid.y;
    let r_xorig = NREG * job.stride * wid.y + 7u * job.stride;
    let base_t = wid.x * TILE;

    let up_w = planes[UP_P + d];
    let up_s = fp[UP_S + d];
    let up_b = fp[UP_BI + d];

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (d < EDIM) {
            var acc: f32 = 0.0;
            if (t < T) {
                let kind = tok_kind(off, t);
                for (var f: u32 = 0u; f < NFIELD; f = f + 1u) {
                    // Word hashes are undefined on non-word tokens; feeding
                    // bucket 0 into every symbol would alias them together.
                    if ((f == 4u || f == 5u) && kind != 0u) { continue; }
                    let row = FIELD_ROW[f] + field_id(off, t, f);
                    acc = acc + wgt(EMB_P, EMB_W, EMB_B, row * EDIM + d, fp[EMB_S + f]);
                }
                let flags = tok_flags(off, t);
                for (var b: u32 = 0u; b < NFLAG; b = b + 1u) {
                    if (((flags >> b) & 1u) == 1u) {
                        acc = acc + wgt(EMB_P, EMB_W, EMB_B,
                                        (FLAG_ROW + b) * EDIM + d, fp[EMB_S + NFIELD]);
                    }
                }
            }
            tA[j * EDIM + d] = acc;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let v = up_b + up_s * dotA32(up_w, j * EDIM);
            hid[hbase + t * DIM + d] = v;
            scratch[r_xorig + t * DIM + d] = v;
        }
    }
}


// ---- document signature and FiLM --------------------------------------------
// A linear probe recovers the language from this pooled signature at 84%
// accuracy, and the model was previously only able to use that at the very last
// layer. These two passes compute it once and turn it into a per-layer, per-
// channel scale and shift, so it reaches the depthwise conv and the recurrence.
@compute @workgroup_size(64)
fn sig_pool(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let r_film = NREG * job.stride * wid.y + 6u * job.stride;

    var s: f32 = 0.0;
    var mx: f32 = -3.4e38;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let v = hid[hbase + t * DIM + d];
        s = s + v;
        mx = max(mx, v);
    }
    scratch[r_film + d] = s / max(1.0, f32(T));
    scratch[r_film + DIM + d] = mx;
}

@compute @workgroup_size(64)
fn film(@builtin(local_invocation_id) lid: vec3<u32>,
        @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let r_film = NREG * job.stride * wid.y + 6u * job.stride;

    // Signature into workgroup memory, RMS-normalized. Without the norm the
    // projection below saturates tanh for most units and stops distinguishing
    // documents at all.
    tA[d] = scratch[r_film + d];
    tA[DIM + d] = scratch[r_film + DIM + d];
    workgroupBarrier();
    var ss: f32 = 0.0;
    for (var k: u32 = 0u; k < 2u * DIM; k = k + 1u) { ss = ss + tA[k] * tA[k]; }
    let inv = inverseSqrt(ss / f32(2u * DIM) + 1e-6);
    let n0 = tA[d] * inv * fp[FN_F + d];
    let n1 = tA[DIM + d] * inv * fp[FN_F + DIM + d];
    workgroupBarrier();
    tA[d] = n0;
    tA[DIM + d] = n1;
    workgroupBarrier();
    if (d < FILM_RANK) {
        red[d] = tanh_s(fp[FD_BI + d] + fp[FD_S + d] * dotA128(
            planes[FD_P + d * 4u], planes[FD_P + d * 4u + 1u],
            planes[FD_P + d * 4u + 2u], planes[FD_P + d * 4u + 3u], 0u));
    } else {
        red[d] = 0.0;
    }
    workgroupBarrier();

    // 2 * DIM outputs per layer, spread across the 64 threads.
    let n_out = NLAYER * 2u * DIM;
    for (var o = d; o < n_out; o = o + 64u) {
        let raw = fp[FU_BI + o] + fp[FU_S + o] * dotRed32(planes[FU_P + o]);
        let l = o / (2u * DIM);
        let rem = o % (2u * DIM);
        let c = rem % DIM;
        let str = fp[FS_F + l * DIM + c];
        // k == 0 is the scale (identity at strength 0), k == 1 the shift.
        let v = select(str * tanh_s(raw), 1.0 + str * tanh_s(raw), rem < DIM);
        scratch[r_film + 2u * DIM + o] = v;
    }
}


// ---- layer 0 -------------------------------------------------------------

@compute @workgroup_size(64)
fn l0_pre(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_film = sbase + 6u * job.stride;
    let base_t = wid.x * TILE;

    let gain = fp[4302u + d];
    // FiLM for this layer: scale and shift produced from the document signature.
    let gamma = scratch[r_film + 2u * DIM + (0u * 2u + 0u) * DIM + d];
    let beta = scratch[r_film + 2u * DIM + (0u * 2u + 1u) * DIM + d];
    // Normalize this tile plus its two-token halo, so the depthwise window has
    // the values it needs without a separate pass over the whole sequence.
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], t < T);
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            scratch[r_nrm + t * DIM + d] =
                (tA[j * DIM + d] * red[j] * gain) * gamma + beta;
        }
    }
}

@compute @workgroup_size(64)
fn l0_conv(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let pic0 = planes[3652u + d * 2u];
    let pic1 = planes[3652u + d * 2u + 1u];
    let pig0 = planes[3652u + (DIM + d) * 2u];
    let pig1 = planes[3652u + (DIM + d) * 2u + 1u];
    let sc = fp[1099u + d];
    let sg = fp[1099u + DIM + d];
    let bc = fp[1227u + d];
    let bg = fp[1227u + DIM + d];
    let dbias = fp[1035u + d];
    let dws = fp[971u + d];
    var dwv: array<f32, 5>;
    for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
        dwv[k] = wgt(3612u, 10u, 4u, d * KSIZE + k, dws);
    }

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        var acc: f32 = 0.0;
        if (t < T) {
            acc = dbias;
            for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
                let o = i32(t) + (i32(k) - i32(KSIZE / 2u)) * 1;
                if (o >= 0 && o < i32(T)) {
                    acc = acc + dwv[k] * scratch[r_nrm + u32(o) * DIM + d];
                }
            }
        }
        tA[j * DIM + d] = acc;
    }
    workgroupBarrier();

    // Low-rank input-conditioned erase. tB is zero-padded to 32 values so the
    // packed up projection remains word-aligned for ranks below 32.
    if (d < 32u) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            let t = base_t + j;
            var v: f32 = 0.0;
            if (t < T && d < 8u) {
                let raw = fp[1491u + d] + fp[1483u + d] * dotA64(
                    planes[4164u + d * 2u], planes[4164u + d * 2u + 1u],
                    j * DIM);
                v = tanh_s(raw);
            }
            tB[j * 2u * DIM + d] = v;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let ef = fp[1627u + d] + fp[1499u + d] * dotB32(
                planes[4180u + d], j * 2u * DIM);
            let eb = fp[1627u + DIM + d] + fp[1499u + DIM + d] * dotB32(
                planes[4180u + DIM + d], j * 2u * DIM);
            scratch[r_fw + t * DIM + d] = sigmoid_s(ef);
            scratch[r_bw + t * DIM + d] = sigmoid_s(eb);
        }
    }
    workgroupBarrier();

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let cand = bc + sc * dotA64(pic0, pic1, j * DIM);
            let gate = bg + sg * dotA64(pig0, pig1, j * DIM);
            scratch[r_b + t * DIM + d] = tanh_s(cand) * sigmoid_s(gate);
        }
    }
}


@compute @workgroup_size(64)
fn l0_scan(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;

    let base_f = sigmoid_s(fp[4174u + d]);
    let base_b = sigmoid_s(fp[4238u + d]);
    var hf: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let bt = scratch[r_b + t * DIM + d];
        let aft = base_f * (1.0 - scratch[r_fw + t * DIM + d]);
        hf = aft * hf + bt;
        scratch[r_fw + t * DIM + d] = hf;
    }
    var hb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        let bt = scratch[r_b + ti * DIM + d];
        let abt = base_b * (1.0 - scratch[r_bw + ti * DIM + d]);
        hb = abt * hb + bt;
        scratch[r_bw + ti * DIM + d] = hb;
    }
}


@compute @workgroup_size(64)
fn l0_post(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let po0 = planes[3908u + d * 4u];
    let po1 = planes[3908u + d * 4u + 1u];
    let po2 = planes[3908u + d * 4u + 2u];
    let po3 = planes[3908u + d * 4u + 3u];
    let spo = fp[1355u + d];
    let bpo = fp[1419u + d];
    let og = sigmoid_s(fp[4110u + d]);

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            tB[j * 2u * DIM + d]       = scratch[r_fw + t * DIM + d];
            tB[j * 2u * DIM + DIM + d] = scratch[r_bw + t * DIM + d];
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let y = bpo + spo * dotB128(po0, po1, po2, po3, j * 2u * DIM);
            hid[hbase + t * DIM + d] = hid[hbase + t * DIM + d] + y * og;
        }
    }
}


// ---- layer 1 -------------------------------------------------------------

@compute @workgroup_size(64)
fn l1_pre(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_film = sbase + 6u * job.stride;
    let base_t = wid.x * TILE;

    let gain = fp[4558u + d];
    // FiLM for this layer: scale and shift produced from the document signature.
    let gamma = scratch[r_film + 2u * DIM + (1u * 2u + 0u) * DIM + d];
    let beta = scratch[r_film + 2u * DIM + (1u * 2u + 1u) * DIM + d];
    // Normalize this tile plus its two-token halo, so the depthwise window has
    // the values it needs without a separate pass over the whole sequence.
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], t < T);
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            scratch[r_nrm + t * DIM + d] =
                (tA[j * DIM + d] * red[j] * gain) * gamma + beta;
        }
    }
}

@compute @workgroup_size(64)
fn l1_conv(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let pic0 = planes[4348u + d * 2u];
    let pic1 = planes[4348u + d * 2u + 1u];
    let pig0 = planes[4348u + (DIM + d) * 2u];
    let pig1 = planes[4348u + (DIM + d) * 2u + 1u];
    let sc = fp[1883u + d];
    let sg = fp[1883u + DIM + d];
    let bc = fp[2011u + d];
    let bg = fp[2011u + DIM + d];
    let dbias = fp[1819u + d];
    let dws = fp[1755u + d];
    var dwv: array<f32, 5>;
    for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
        dwv[k] = wgt(4308u, 10u, 4u, d * KSIZE + k, dws);
    }

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        var acc: f32 = 0.0;
        if (t < T) {
            acc = dbias;
            for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
                let o = i32(t) + (i32(k) - i32(KSIZE / 2u)) * 2;
                if (o >= 0 && o < i32(T)) {
                    acc = acc + dwv[k] * scratch[r_nrm + u32(o) * DIM + d];
                }
            }
        }
        tA[j * DIM + d] = acc;
    }
    workgroupBarrier();

    // Low-rank input-conditioned erase. tB is zero-padded to 32 values so the
    // packed up projection remains word-aligned for ranks below 32.
    if (d < 32u) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            let t = base_t + j;
            var v: f32 = 0.0;
            if (t < T && d < 8u) {
                let raw = fp[2275u + d] + fp[2267u + d] * dotA64(
                    planes[4860u + d * 2u], planes[4860u + d * 2u + 1u],
                    j * DIM);
                v = tanh_s(raw);
            }
            tB[j * 2u * DIM + d] = v;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let ef = fp[2411u + d] + fp[2283u + d] * dotB32(
                planes[4876u + d], j * 2u * DIM);
            let eb = fp[2411u + DIM + d] + fp[2283u + DIM + d] * dotB32(
                planes[4876u + DIM + d], j * 2u * DIM);
            scratch[r_fw + t * DIM + d] = sigmoid_s(ef);
            scratch[r_bw + t * DIM + d] = sigmoid_s(eb);
        }
    }
    workgroupBarrier();

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let cand = bc + sc * dotA64(pic0, pic1, j * DIM);
            let gate = bg + sg * dotA64(pig0, pig1, j * DIM);
            scratch[r_b + t * DIM + d] = tanh_s(cand) * sigmoid_s(gate);
        }
    }
}


@compute @workgroup_size(64)
fn l1_scan(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;

    let base_f = sigmoid_s(fp[4430u + d]);
    let base_b = sigmoid_s(fp[4494u + d]);
    var hf: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let bt = scratch[r_b + t * DIM + d];
        let aft = base_f * (1.0 - scratch[r_fw + t * DIM + d]);
        hf = aft * hf + bt;
        scratch[r_fw + t * DIM + d] = hf;
    }
    var hb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        let bt = scratch[r_b + ti * DIM + d];
        let abt = base_b * (1.0 - scratch[r_bw + ti * DIM + d]);
        hb = abt * hb + bt;
        scratch[r_bw + ti * DIM + d] = hb;
    }
}


@compute @workgroup_size(64)
fn l1_post(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let po0 = planes[4604u + d * 4u];
    let po1 = planes[4604u + d * 4u + 1u];
    let po2 = planes[4604u + d * 4u + 2u];
    let po3 = planes[4604u + d * 4u + 3u];
    let spo = fp[2139u + d];
    let bpo = fp[2203u + d];
    let og = sigmoid_s(fp[4366u + d]);

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            tB[j * 2u * DIM + d]       = scratch[r_fw + t * DIM + d];
            tB[j * 2u * DIM + DIM + d] = scratch[r_bw + t * DIM + d];
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let y = bpo + spo * dotB128(po0, po1, po2, po3, j * 2u * DIM);
            hid[hbase + t * DIM + d] = hid[hbase + t * DIM + d] + y * og;
        }
    }
}


// ---- layer 2 -------------------------------------------------------------

@compute @workgroup_size(64)
fn l2_pre(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_film = sbase + 6u * job.stride;
    let base_t = wid.x * TILE;

    let gain = fp[4814u + d];
    // FiLM for this layer: scale and shift produced from the document signature.
    let gamma = scratch[r_film + 2u * DIM + (2u * 2u + 0u) * DIM + d];
    let beta = scratch[r_film + 2u * DIM + (2u * 2u + 1u) * DIM + d];
    // Normalize this tile plus its two-token halo, so the depthwise window has
    // the values it needs without a separate pass over the whole sequence.
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], t < T);
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            scratch[r_nrm + t * DIM + d] =
                (tA[j * DIM + d] * red[j] * gain) * gamma + beta;
        }
    }
}

@compute @workgroup_size(64)
fn l2_conv(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let pic0 = planes[5044u + d * 2u];
    let pic1 = planes[5044u + d * 2u + 1u];
    let pig0 = planes[5044u + (DIM + d) * 2u];
    let pig1 = planes[5044u + (DIM + d) * 2u + 1u];
    let sc = fp[2667u + d];
    let sg = fp[2667u + DIM + d];
    let bc = fp[2795u + d];
    let bg = fp[2795u + DIM + d];
    let dbias = fp[2603u + d];
    let dws = fp[2539u + d];
    var dwv: array<f32, 5>;
    for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
        dwv[k] = wgt(5004u, 10u, 4u, d * KSIZE + k, dws);
    }

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        var acc: f32 = 0.0;
        if (t < T) {
            acc = dbias;
            for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
                let o = i32(t) + (i32(k) - i32(KSIZE / 2u)) * 4;
                if (o >= 0 && o < i32(T)) {
                    acc = acc + dwv[k] * scratch[r_nrm + u32(o) * DIM + d];
                }
            }
        }
        tA[j * DIM + d] = acc;
    }
    workgroupBarrier();

    // Low-rank input-conditioned erase. tB is zero-padded to 32 values so the
    // packed up projection remains word-aligned for ranks below 32.
    if (d < 32u) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            let t = base_t + j;
            var v: f32 = 0.0;
            if (t < T && d < 8u) {
                let raw = fp[3059u + d] + fp[3051u + d] * dotA64(
                    planes[5556u + d * 2u], planes[5556u + d * 2u + 1u],
                    j * DIM);
                v = tanh_s(raw);
            }
            tB[j * 2u * DIM + d] = v;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let ef = fp[3195u + d] + fp[3067u + d] * dotB32(
                planes[5572u + d], j * 2u * DIM);
            let eb = fp[3195u + DIM + d] + fp[3067u + DIM + d] * dotB32(
                planes[5572u + DIM + d], j * 2u * DIM);
            scratch[r_fw + t * DIM + d] = sigmoid_s(ef);
            scratch[r_bw + t * DIM + d] = sigmoid_s(eb);
        }
    }
    workgroupBarrier();

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let cand = bc + sc * dotA64(pic0, pic1, j * DIM);
            let gate = bg + sg * dotA64(pig0, pig1, j * DIM);
            scratch[r_b + t * DIM + d] = tanh_s(cand) * sigmoid_s(gate);
        }
    }
}


@compute @workgroup_size(64)
fn l2_scan(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;

    let base_f = sigmoid_s(fp[4686u + d]);
    let base_b = sigmoid_s(fp[4750u + d]);
    var hf: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let bt = scratch[r_b + t * DIM + d];
        let aft = base_f * (1.0 - scratch[r_fw + t * DIM + d]);
        hf = aft * hf + bt;
        scratch[r_fw + t * DIM + d] = hf;
    }
    var hb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        let bt = scratch[r_b + ti * DIM + d];
        let abt = base_b * (1.0 - scratch[r_bw + ti * DIM + d]);
        hb = abt * hb + bt;
        scratch[r_bw + ti * DIM + d] = hb;
    }
}


@compute @workgroup_size(64)
fn l2_post(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let po0 = planes[5300u + d * 4u];
    let po1 = planes[5300u + d * 4u + 1u];
    let po2 = planes[5300u + d * 4u + 2u];
    let po3 = planes[5300u + d * 4u + 3u];
    let spo = fp[2923u + d];
    let bpo = fp[2987u + d];
    let og = sigmoid_s(fp[4622u + d]);

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            tB[j * 2u * DIM + d]       = scratch[r_fw + t * DIM + d];
            tB[j * 2u * DIM + DIM + d] = scratch[r_bw + t * DIM + d];
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let y = bpo + spo * dotB128(po0, po1, po2, po3, j * 2u * DIM);
            hid[hbase + t * DIM + d] = hid[hbase + t * DIM + d] + y * og;
        }
    }
}


// ---- file-scale context ----------------------------------------------------
@compute @workgroup_size(64)
fn pool_reduce(@builtin(local_invocation_id) lid: vec3<u32>,
               @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_pre = sbase;                       // reuses the normalized-input region
    let r_suf = sbase + job.stride;          // reuses the scan-input region
    let r_stat = sbase + 5u * job.stride;

    let dgw = fp[4878u + d];
    var s: f32 = 0.0;    // plain sum, still feeds the sequence-mean stat below
    var sg: f32 = 0.0;   // decl-gated sum, feeds the prefix mean only
    var sdg: f32 = 0.0;
    var mx: f32 = -3.4e38;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let v = hid[hbase + t * DIM + d];
        s = s + v;
        mx = max(mx, v);
        let dg = sigmoid_s(v * dgw);
        sg = sg + v * dg;
        sdg = sdg + dg;
        scratch[r_pre + t * DIM + d] = sg / max(1.0, sdg);
    }
    var sb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        sb = sb + hid[hbase + ti * DIM + d];
        scratch[r_suf + ti * DIM + d] = sb / f32(t + 1u);
    }
    scratch[r_stat + d] = s / max(1.0, f32(T));
    scratch[r_stat + DIM + d] = mx;
}


@compute @workgroup_size(64)
fn pool_apply(@builtin(local_invocation_id) lid: vec3<u32>,
              @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_pre = sbase;
    let r_suf = sbase + job.stride;
    let r_ctx = sbase + 4u * job.stride;
    let r_stat = sbase + 5u * job.stride;
    let base_t = wid.x * TILE_POOL;

    let gs0 = planes[GS_P + d * 8u];
    let gs1 = planes[GS_P + d * 8u + 1u];
    let gs2 = planes[GS_P + d * 8u + 2u];
    let gs3 = planes[GS_P + d * 8u + 3u];
    let gs4 = planes[GS_P + d * 8u + 4u];
    let gs5 = planes[GS_P + d * 8u + 5u];
    let gs6 = planes[GS_P + d * 8u + 6u];
    let gs7 = planes[GS_P + d * 8u + 7u];
    let gss = fp[GS_S + d];
    let gsb = fp[GS_BI + d];
    let gg0 = planes[GG_P + d * 2u];
    let gg1 = planes[GG_P + d * 2u + 1u];
    let ggs = fp[GG_S + d];
    let ggb = fp[GG_BI + d];

    for (var j: u32 = 0u; j < TILE_POOL; j = j + 1u) {
        let t = base_t + j;
        let ok = t < T;
        tP[j * 4u * DIM + d]             = scratch[r_stat + d];
        tP[j * 4u * DIM + DIM + d]       = scratch[r_stat + DIM + d];
        tP[j * 4u * DIM + 2u * DIM + d]  = select(0.0, scratch[r_pre + t * DIM + d], ok);
        tP[j * 4u * DIM + 3u * DIM + d]  = select(0.0, scratch[r_suf + t * DIM + d], ok);
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], ok);
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE_POOL; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let b = j * 4u * DIM;
            var acc: f32 = 0.0;
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs0, k, tP[b + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs1, k, tP[b + 32u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs2, k, tP[b + 64u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs3, k, tP[b + 96u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs4, k, tP[b + 128u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs5, k, tP[b + 160u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs6, k, tP[b + 192u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs7, k, tP[b + 224u + k]); }
            let ctx = tanh_s(gsb + gss * acc);
            let g = sigmoid_s(ggb + ggs * dotA64(gg0, gg1, j * DIM));
            scratch[r_ctx + t * DIM + d] = ctx * g;
        }
    }
}

// ---- classifier head -------------------------------------------------------
@compute @workgroup_size(64)
fn head(@builtin(local_invocation_id) lid: vec3<u32>,
        @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let off = job.token_offset;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_ctx = sbase + 4u * job.stride;
    let r_xorig = sbase + 7u * job.stride;
    let base_t = wid.x * TILE;

    let hgain = fp[HNORM_F + d];
    let o0 = d;
    let o1 = DIM + d;
    let h0a = planes[HH_P + o0 * 4u];
    let h0b = planes[HH_P + o0 * 4u + 1u];
    let h0c = planes[HH_P + o0 * 4u + 2u];
    let h0d = planes[HH_P + o0 * 4u + 3u];
    var h1a: u32 = 0u; var h1b: u32 = 0u; var h1c: u32 = 0u; var h1d: u32 = 0u;
    if (o1 < HEAD_HIDDEN) {
        h1a = planes[HH_P + o1 * 4u];
        h1b = planes[HH_P + o1 * 4u + 1u];
        h1c = planes[HH_P + o1 * 4u + 2u];
        h1d = planes[HH_P + o1 * 4u + 3u];
    }
    // head_out is 9 rows; thread c owns class c, so the final matmul is nine
    // parallel dots rather than one thread doing all of them.
    var ho0: u32 = 0u; var ho1: u32 = 0u; var ho2: u32 = 0u;
    if (d < NCLASS) {
        ho0 = planes[HO_P + d * 3u];
        ho1 = planes[HO_P + d * 3u + 1u];
        ho2 = planes[HO_P + d * 3u + 2u];
    }

    // The pre-layer embedding folded back in at strength fp[HW_F] -- zero
    // unless the checkpoint has a highway_scale parameter, in which case it
    // gives the classifier a direct path to the raw token identity alongside
    // whatever the recurrent layers built on top of it.
    let hw: f32 = fp[HW_F];
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        let xv = select(0.0, hid[hbase + t * DIM + d], t < T);
        let xo = select(0.0, scratch[r_xorig + t * DIM + d], t < T);
        tA[j * DIM + d] = xv + hw * xo;
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tB[j * 2u * DIM + d] = tA[j * DIM + d] * red[j] * hgain;
        tB[j * 2u * DIM + DIM + d] = select(0.0, scratch[r_ctx + t * DIM + d], t < T);
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let a0 = fp[HH_BI + o0] + fp[HH_S + o0] * dotB128(h0a, h0b, h0c, h0d, j * 2u * DIM);
        let c0 = 0.7978845608 * (a0 + 0.044715 * a0 * a0 * a0);
        tA[j * HEAD_HIDDEN + o0] = 0.5 * a0 * (1.0 + tanh_s(c0));
        if (o1 < HEAD_HIDDEN) {
            let a1 = fp[HH_BI + o1] + fp[HH_S + o1] * dotB128(h1a, h1b, h1c, h1d, j * 2u * DIM);
            let c1 = 0.7978845608 * (a1 + 0.044715 * a1 * a1 * a1);
            tA[j * HEAD_HIDDEN + o1] = 0.5 * a1 * (1.0 + tanh_s(c1));
        }
    }
    workgroupBarrier();
    if (d < NCLASS) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            lg[j * NCLASS + d] = fp[HO_BI + d] + fp[HO_S + d]
                * dotA96(ho0, ho1, ho2, j * HEAD_HIDDEN);
        }
    }
    workgroupBarrier();
    if (d < TILE) {
        let t = base_t + d;
        if (t < T) {
            var best: u32 = 0u;
            var bestv: f32 = lg[d * NCLASS];
            for (var c: u32 = 1u; c < NCLASS; c = c + 1u) {
                let v = lg[d * NCLASS + c];
                if (v > bestv) { bestv = v; best = c; }
            }
            out_cls[off + t] = best;
        }
    }
}
